Create an empty RendezvousGame.vue, rename Game.vue to ClassicGame.vue
mibpl/StreetViewGame pull request #40
Opened 2021-03-06 15:35 UTC by enkait

Also sets up separate routes for the two game modes. The Lobby.vue code queries the game_mode entry in the game database to decide where to route to at game start.
This is a followup to #39 and is of course needed for #37 .

2021-03-09 12:42 UTC, anula requested changes

2021-03-09 12:42 UTC, anula commented on src/views/ClassicGame.vue
> +        v-bind:guessingEnabled="true"
I don't see this prop (guessingEnabled) in the MakerMap.

2021-03-09 12:42 UTC, anula commented on src/views/Lobby.vue
> +                    'Create a new room.',
Why doesn't this have a confirm action that redirects to main? I think currently the user can just disable the dialog and stay in this room.

2021-03-09 12:42 UTC, anula commented on src/views/Main.vue
> +        options: {
Shouldn't this be set in Lobby (it is fine if it is in later CLs). It seems to me it can be an undefined option in Lobby, it should exist only in actual Game.

2021-03-13 20:08 UTC, enkait commented on src/views/Lobby.vue
> +                    'Create a new room.',
Done.

2021-03-13 21:36 UTC, enkait commented on src/views/Main.vue
> +        options: {
Ok, I agree it should be possible and if so I'll remove this in a future change (#41).

2021-03-13 21:53 UTC, enkait commented on src/views/ClassicGame.vue
> +        v-bind:guessingEnabled="true"
Removed.

2021-03-14 17:58 UTC, anula approved these changes

2021-03-14 17:58 UTC, merged